### ISSUE TITLE
Misc Improvements

### ISSUE THREAD

**Issue by tferr** [scijava/script-editor-jython#9]
A couple of (minor) things that need to improved: 
- [x] Currently, there are many debug Messages being printed to the console that will not make sense to most users. These can flood the console quite quickly. Examples:
  -  https://github.com/scijava/script-editor-jython/blob/f099d7a91248e0c85b5cfed345cc04c1019e152c/src/main/java/org/scijava/plugins/scripteditor/jython/JythonScriptParser.java#L174
  - https://github.com/scijava/script-editor-jython/blob/f099d7a91248e0c85b5cfed345cc04c1019e152c/src/main/java/org/scijava/plugins/scripteditor/jython/JythonScriptParser.java#L201
  - https://github.com/scijava/script-editor-jython/blob/f099d7a91248e0c85b5cfed345cc04c1019e152c/src/main/java/org/scijava/plugins/scripteditor/jython/StaticDotAutocompletions.java#L57
- [x] Frequent NPE  (stack trace below)

<details>
<summary>java.lang.NullPointerException</summary>

```
Failed to get autocompletions from org.scijava.plugins.scripteditor.jython.JythonAutoCompletions@6bf193f0
java.lang.NullPointerException
	at org.scijava.plugins.scripteditor.jython.JythonAutoCompletions.completionsFor(JythonAutoCompletions.java:219)
	at org.scijava.plugins.scripteditor.jython.JythonAutocompletionProvider.getCompletionsImpl(JythonAutocompletionProvider.java:108)
	at org.fife.ui.autocomplete.CompletionProviderBase.getCompletions(CompletionProviderBase.java:98)
	at org.fife.ui.autocomplete.AutoCompletion.refreshPopupWindow(AutoCompletion.java:833)
	at org.fife.ui.autocomplete.AutoCompletion$AutoCompleteAction.actionPerformed(AutoCompletion.java:1402)
	at javax.swing.SwingUtilities.notifyAction(SwingUtilities.java:1668)
	at javax.swing.JComponent.processKeyBinding(JComponent.java:2882)
	at javax.swing.JComponent.processKeyBindings(JComponent.java:2929)
	at javax.swing.JComponent.processKeyEvent(JComponent.java:2845)
	at java.awt.Component.processEvent(Component.java:6316)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1954)
	at java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:835)
	at java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1103)
	at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:974)
	at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:800)
	at java.awt.Component.dispatchEventImpl(Component.java:4760)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Failed to get autocompletions from org.scijava.plugins.scripteditor.jython.JythonAutoCompletions@6bf193f0
```
-</details>

**Comment by acardona** [comment]
I've pushed a number of fixes that hide away most debugging messages by default. This package is still in beta, so the ability to collect error messages from users will be useful. There is a `JythonAutocompletionProvider.debug` static integer that, when 0, hides everything; when 1 (default) shows little, and when 2 shows everything, including exceptions and deeper messages useful for finding out what happened where.
Not yet released.

**Comment by acardona** [comment]
Now I've pushed even more, but I can't release it, not even like this:

```
jython-autocompletion (main)$ ../scijava-scripts/release-version.sh --skip-version-check --skip-branch-check
```

The release script runs into incomprehensible errors. First, can't seem to get the version number right (an error appears in the square brackets where the version number should be). Second, some mysterious task fails to run, so have to skip the version check altogether. Third, the "main" branch (created by @ctrueden in the new repository under the scijava organization) is not recognized as a master branch, so I have to skip that. Finally, the system gives up because it can't find script-editor 0.6.2 even though it is released, and I can't pass the -U tag to mvn because the release script handles that, short of editing the release script itself. So stuck, again. Takes longer to release a project than to add features to it: this is not a healthy framework.

**Comment by tferr** [comment]
closing this, as the issues seem to be now fixed
